### ISSUE TITLE
Tabs with error: This page requires data from services that are currently unavailable

### ISSUE THREAD

**Issue by tomsherrod** [cloudfoundry-community/admin-ui-boshrelease#45]
I've got an odd issue. See the lower end of [this thread.](https://github.com/cloudfoundry-incubator/admin-ui/issues/156)

A boshrelease deploy has the error in the tabs: Organizations, Spaces, Service Instances, Service Bindings, Service Keys, Service Plan, Service Plan Visibilities.
A manual deploy of admin-ui does not. Verified the default.yml settings in both.

Does the boshrelease use a back version of the admin-ui? Pointers appreciated.

**Comment by tyyko** [comment]
I would say that this issue is caused by insufficient scopes on the uaa client as suggested [here](https://github.com/cloudfoundry-incubator/admin-ui/issues/156#issuecomment-205791486).

 [The used uaa client setup](https://github.com/cloudfoundry-community/admin-ui-boshrelease/blob/master/jobs/register_admin_ui/templates/bin/register_admin_ui#L18-L22) is not up to date with the [readme](https://github.com/cloudfoundry-incubator/admin-ui/blob/master/README.md#setup-administration-ui-group-and-user-using-uaac)

I am working on that

**Comment by tyyko** [comment]
The last update solved all issues on my side, if you still have problems connecting to the ccdb, please check if you are using the right port and address. 

Feel free to reopen the issue this does not solve your problem
