### ISSUE TITLE
Location of UAAC client

### ISSUE THREAD

**Issue by chrisrana** [cloudfoundry-community/admin-ui-boshrelease#46]
Admin UI errand job runs UAAC command.Where this UAAC is installed? I searched in it in cloud controller and admin ui vm i didn't find it.

After running errand job i am getting Insufficient scope error.I want to manually run some uaac. I can install uaac client but curious know how errand job is running uaac command.

**Comment by tyyko** [comment]
Hello, [this code](https://github.com/cloudfoundry-community/admin-ui-boshrelease/blob/master/jobs/register_admin_ui/templates/helpers/ctl_setup.sh#L24-L28) puts on path all binaries on the release packages.

[Here](https://github.com/cloudfoundry-community/admin-ui-boshrelease/tree/master/packages/uaac) you can find the uaa client package and [here](https://github.com/cloudfoundry-community/admin-ui-boshrelease/tree/master/src/uaac) is the 'source' location (on quotes because it's only the gem file).
